import Head from 'next/head';

import { Inter } from 'next/font/google';

export default function Home() {
  const getData = async (e) => {
    e.preventDefault();
    const data = { id: e.target.dossierID.value };

    try {
      const response = await fetch('/api/getData', {
        method: 'POST',
        mode: 'cors',
        cache: 'no-cache',
        credentials: 'same-origin',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });
      const responseData = await response.json();
      console.log(responseData);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={getData}>
        <input type="" name="dossierID" label="dossierID" />
        <button>Envoyer</button>
      </form>
    </>
  );
}
